# https://stackoverflow.com/questions/73687176/permission-denied-to-github-actionsbot-the-requested-url-returned-error-403

name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash for the release branch (optional)'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        git config credential.helper 'store --file=.git-credentials'
        echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > .git-credentials
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch 'develop' branch
      run: git fetch origin develop:develop

    - name: Delete existing 'release' branch on remote
      run: git push --delete origin release || echo "Branch does not exist on remote"

    - name: Phase 1 - Create Release Branch
      id: phase1
      run: |
        commit_hash=${{ inputs.commit_hash }}
        git checkout develop
        git pull origin develop

        if [ -n "$commit_hash" ]; then
          git fetch origin $commit_hash && git checkout $commit_hash
        fi

        git checkout -b release
        git push -u origin release --force

    - name: Phase 2 - Your Second Command
      run: |
        # Your second command here

    - name: Phase 3 - Your Third Command
      run: |
        # Your third command here
